{% set version = "0.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-autoplotly
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/autoplotly_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/autoplotly/autoplotly_{{ version }}.tar.gz
  sha256: fc6cd128f8ca3f4d0b4c57bd7c6981dac4641f54a51c9331e7c51f4c14a5e782

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-ggfortify
    - r-ggplot2
    - r-plotly

  run:
    - r-base
    - r-ggfortify
    - r-ggplot2
    - r-plotly

test:
  commands:
    - $R -e "library('autoplotly')"           # [not win]
    - "\"%R%\" -e \"library('autoplotly')\""  # [win]

about:
  home: https://github.com/terrytangyuan/autoplotly
  license: GPL-2.0-only
  summary: Functionalities to automatically generate interactive visualizations for popular statistical results supported by 'ggfortify', such as time series, PCA, clustering and survival analysis, with 'plotly.js' <https://plot.ly/> and 'ggplot2' style. The generated visualizations can also be easily extended using 'ggplot2'
    and 'plotly' syntax while staying interactive.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
