travis:
  secure:
    BINSTAR_TOKEN: Rx8J0Xlln9R3yhbp0IIg1vHO+2JhOMI+mkdELY7LUGLNPJ/BiBebJ1PmKikTb/0dT6zBlTlndO15/UkoJcRGdCUGvC+MIxED9RnE+zo4c0LFytF/rjQquCEifCSllqDV/8rEn+XLsyw1WMZT4LELTHNzBAvrKN98kpBVR75A/SCeoAeC+4LQ90s1A3UzHtPZinYyRcmH44VeN0gbhtAYR7ThQ8N6QbuUvhq//WdvzYT1m0iwmH20evOBwY4yjwOnxFSFUZIgA24KofLtgzXq0BVZaJhNd/1VVXXRhZJdbv7bbrUX8WEJLJRL/xLsyz5MXnnHQYhb/o+IL/w35kneh2PxHkkzyYi9qgPl1FhgrTXYJI2E91nsWH4LRGl8YWgd1qpREjSFBNhP8aFhbgpW+XYb+AMBCEAkuK3llQFQcjB5Ei3nvpIFzvlNicoXcpzxlupH8JDGc+jwSTUd45Hgummms4sPBerUd5AJIwbkkZH+ME9LauNg0UbiZuV62h1bO7Q4bNmz4Cfh5GAUHIBYA7rmBq2YtDQ+cWod1CCXuEZpSc+JXpuHZaSfCbk5Rv/67rIUX7aJPkYdF6hHDP9IdIpVdrNTiYPcYKfqo0LYT4NE5ySxobiYOzxg4Sx6tDqdPz81YUULQcyYE4vVN/pagaUMwxGJbHctoHl3+WlByhw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
