travis:
  secure:
    BINSTAR_TOKEN: Mk76gomuLWac1KU2LL4ZbW3vSLm5/PmTjYN1BF4hSz3pwIQzrFynZybBotFIP5hHmNQrpsNYD3bxAkXRkvBO1DvAY9GMvSqaNPcJwTMXQ68EwXVDwwjwctxXU+diUJ0KfNAAdhkZvW+3eRQrAQTjLUGTJC8P2MGvc6WBzZIwYgl4Sl4v+m348DIo8YNYZ0z4wmk2BXcB6kYVcPJ7bh6LZqDFau9+sbuPcgWjLvMK8PN0lt1Zx3JcYc9j0In0jdNdKeGYJSFL5F0gz+rX24i1oxBlYnNnRLjn4LFCcR4Xn2mWDomX2nCaXo7vXgLJzWxXd26LXQQDhCyDpDMCwt/8TKr5d0kpmokV0FGjHXWpky5XjSCT+hV7/dCiIb698pwx6I/rSQ9wHtQJi9ChOMu9uAMhp6nROoSwtQiqFBAPL/EDm6RN9vXCrazv03RWU5aWgDfjXLDk6+jpMxy7OaS4GOKwO4Mdw1IAaXrBELrWW+QnOili+hipwEBq58qApRHpabPNac/HCMwlSTjK2zqYfLreySwEEWHR4Nt1+Kf5Fvn2mqqKk7CiMs7gfa83rFbMkn1urCA2oHcb0+PSDn1D4Uu0Y0WgoeRVMjB52Sqlyu+GiSAG2jRq7ut13sqr9KOBPeYmxn5kM0etXg+Eu5zyp42cYF6DadEbPW6ey7StiY8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
