travis:
  secure:
    BINSTAR_TOKEN: bQ3UPRLNfQbG9bnNXs8JS3zR1rDbniQom26+W/ICOJ4e/WxFRP7u+JTYeRKIbH2uyx2JGPOvY5qW1/bG+u+3n88dVgRhsF11cfLOarvGcaA0P1DLcEevH+ptNpJlFoqJivpDdOYaYqtczT90DC5PZGdgy3XUK9AJfkfLQ+urQmfAuStkQ1GrXk7BBrBsHDaAxc82qEVqktkACK2+QIyjyZj9yplBxiaoMWqdoWk0owVO4JZmyeoJ/YQj2OTMgVa1WbXXVc18EgkHWlnxBJjRBCtXZXCT9bzQ23sGdN5+XmWC7cSABd9pqV3HYJn/KAVXN1heLh5n8myZVc5zBxmw5JrspLvynQ+yeIWXOhRZLkKq0u5kQ2LUGBtyaszgfk0ighLWjsNKOGvrQxOakqrxz6WydUSyUFnrD2mD6SNF1I81NkymcwG01xApmGV5wRJ0WBQ74UV7zETvFOVkaN9KloRi7lhLE7CEW8a4USFFCA2y3j6+KBtpYV9m8lKEJn5Hlr7weCaZcjpbLhBKhYeTb0td4zh0oPTQpo6jHNK8sFIn1VeD/RLz1u4u8yAMFe0J+3S/oqZwZLdBSozjqltzZIwNcpw6IU/PONuzXJ//xL+a2t+h58EvjjCep2sxA1F1Eyw36/IZmIYPGywhhyW9N8qCdyBq4Go9XgdBr0CzVUU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
