travis:
  secure:
    BINSTAR_TOKEN: Cc6zhqINLEekwhJEtjNcpnD15LT06sQgpXzmkO1UlgRnriV9sXa+ClKGMLgWgxvRADwaPmd2FzzULdi/ARcsqzLBoj+oD9DrzthRAh9X69cTT2oDRT2f6zVgZZ8bG05KsOnlSxAeZClujrf2sjKO7K/lkrwl8VjbzIBvtI6YVJoZrcvV1/ST8dYq4JeiyQJBpmyIfqo1YPPWW9kBF5Ju0VfJDjOiWpfDAvvFmMrai91Ed2l7Nj1S78mRtasAEK9m4hetYqq65iVucH7OQAvvtfYzUSxpERNd/ONwE5nnGS8cP4sbxY2DRy73UY14ozM7qu15mK/6Cs2ia+vTKiWWWQHVulQBUJYqYzmCuSgqg1cvh9wyUkqEPMu5S2wQylD/HzxoNWyKj+DmwCoQnQZJtFtLi1PjX5lK94fbDSfTncFywabRoO9OuaACoheSU1/hEL6VifpOLc6DJRY7i9Ucm4A5ysssG9ZLrqXHUYYo9T3MZS1zqLiz0V/HEVztXL6/Ja2N+htXTFlt2OQ+a3IccYgds29iFDO5vX62grqFXi+1DdHcSdFBEToeG/R6CKo79JqO1xXfhbLXIPHWg59NuJqElWmz+wkYRzY1TVz7DRQy9oXZ8Fuhu9VnoEtwkW5IcwYCJvM6t58pQZxCTTUlFTUugDl0JdU78xAMYsZ5OnI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
