travis:
  secure:
    BINSTAR_TOKEN: Valn1KHTfwnLrZ99Nb2p7SYy83iZxcVs8F6rQF9aGkYK/eQEJfPIqZPpF/GVYt6Mkrjw06BRKTp8iLjMucZua7DLO/DkLpfuDPO+EjWPt7ghYPA0D9XAL26rBWaPSklf9n5EPQ29Z50rkt21k49TbSeF3CFUeSQB41stR8P+m8JHjn5NfBTQIlKm2k/JJp834yTtrgfg6qYw7OeN+9xS01+YBMG5o4bOeKvFvwD+EzVjD3C/EMjLqfO7PKkR39/xBGxNMesCLc0DoKyFCSfnL5vmwlTa7TzaFsjvTpFBjITj7Ecu+FQNql8P/ogf8nqOEue6h9G5V2J7WPgev3sBUX81DrlWmb4qOhazr0RSf55ZzjxsWL8cYGQf2JXfrINoQ4MM2zZ5qiBDgDf8l3IaU8G6MiUIdCZX0CyR2gPpISi0e7+ri8wQLNyhuhZYAzkxVluKZbJEBB1EucrnVsnPbpU/0JF/l+i9WwzX0RbNgva+iuB2K0dWI7jdhRXubUhDHfQOeOD8TMSRn/c1AAZqq2P5TOrzbYGUDy2JP5RE5qW1jK0sCcD2YSehUneTWVQ7hvETZdkGyV9cMtDMQfgjuWr1ABAP2MoS69ub8viH9U2H7RHX+Dl9vgHqRrpJF1Jwk/qQjZ77o0kfEna+Wn5WB6HpTS9+GgQ63sMu+eTiCpM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
